name: project3_udacity
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - numpy=1.23.1
  - pip=20.3.3
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pytest=7.1.3
  - jupyter=1.0.0
  - jupyterlab=3.4.8
  - fastapi=0.63.0
  - uvicorn=0.18.3